title: Ashish James
#logo: /assets/img/headshot_circle.png
description: Fresh graduate with hands-on experience in SQL, Python, Tableau, Power BI, and Excel. Analytical thinker with a keen eye for detail. Effective team player with strong interpersonal skills, capable of collaborating seamlessly to drive datadriven decisions.
# show_downloads: false
theme: jekyll-theme-minimal
